### ISSUE TITLE
KeyError: 'RGBA'报错

### ISSUE THREAD

**Issue by curlfoxs** [15331094/wxImage#7]
OSError: cannot write mode RGBA as JPEG
这个错误是由于什么原因造成的，该如何解决？

**Comment by xufangbing** [comment]
我也碰到同样的问题，解决的方法：

1.参考了这的答案[cannot write mode RGBA as JPEG (4.2.0) #2609](https://github.com/python-pillow/Pillow/issues/2609)。

2.将源代码wxImage.py里面的jpg改成了png，就可以顺利运行，拼成一张图了。

**Comment by zhoutongle** [comment]
可以把RGBA改成RGB，png图像有RGBA四个通道，而JPG图像只有RGB三个通道，所以PNG转BMP时候程序不知道A通道怎么办，就会产生错误。
